//
//  YelpAPIConstants.swift
//  WhatsToEat
//
//  Created by Jay on 5/8/20.
//  Copyright © 2020 JayGabriel. All rights reserved.
//

import Foundation

struct YelpAPIConstants {
    
    // MARK: - Yelp API
    struct Yelp {
        static let AuthorizeURL = "https://api.yelp.com/oauth2/token"
        static let SearchURL = "https://api.yelp.com/v3/businesses/search"
        static let BusinessesURL = "https://api.yelp.com/v3/businesses"
        static let Post = "POST"
        static let Get = "GET"
    }
    
    // MARK: - Restaurant Styles
    // * Version 1.0 will only support styles that are contained in 'ALL' locales
    
    struct CountryStyles {
        static let AD = "AD"
        static let AE = "AE"
        static let AF = "AF"
        static let AG = "AG"
        static let AI = "AI"
        static let AL = "AL"
        static let AM = "AM"
        static let AN = "AN"
        static let AO = "AO"
        static let AQ = "AQ"
        static let AR = "AR"
        static let AS = "AS"
        static let AT = "AT"
        static let AU = "AU"
        static let AW = "AW"
        static let AX = "AX"
        static let AZ = "AZ"
        static let BA = "BA"
        static let BB = "BB"
        static let BD = "BD"
        static let BE = "BE"
        static let BF = "BF"
        static let BG = "BG"
        static let BH = "BH"
        static let BI = "BI"
        static let BJ = "BJ"
        static let BL = "BL"
        static let BM = "BM"
        static let BN = "BN"
        static let BO = "BO"
        static let BR = "BR"
        static let BS = "BS"
        static let BT = "BT"
        static let BV = "BV"
        static let BW = "BW"
        static let BY = "BY"
        static let BZ = "BZ"
        static let CA = "CA"
        static let CC = "CC"
        static let CD = "CD"
        static let CF = "CF"
        static let CG = "CG"
        static let CH = "CH"
        static let CI = "CI"
        static let CK = "CK"
        static let CL = "CL"
        static let CM = "CM"
        static let CN = "CN"
        static let CO = "CO"
        static let CR = "CR"
        static let CU = "CU"
        static let CV = "CV"
        static let CX = "CX"
        static let CY = "CY"
        static let CZ = "CZ"
        static let DE = "DE"
        static let DJ = "DJ"
        static let DK = "DK"
        static let DM = "DM"
        static let DO = "DO"
        static let DZ = "DZ"
        static let EC = "EC"
        static let EE = "EE"
        static let EG = "EG"
        static let EH = "EH"
        static let ER = "ER"
        static let ES = "ES"
        static let ET = "ET"
        static let FI = "FI"
        static let FJ = "FJ"
        static let FK = "FK"
        static let FM = "FM"
        static let FO = "FO"
        static let FR = "FR"
        static let GA = "GA"
        static let GB = "GB"
        static let GD = "GD"
        static let GE = "GE"
        static let GF = "GF"
        static let GG = "GG"
        static let GH = "GH"
        static let GI = "GI"
        static let GL = "GL"
        static let GM = "GM"
        static let GN = "GN"
        static let GP = "GP"
        static let GQ = "GQ"
        static let GR = "GR"
        static let GS = "GS"
        static let GT = "GT"
        static let GU = "GU"
        static let GW = "GW"
        static let GY = "GY"
        static let HK = "HK"
        static let HM = "HM"
        static let HN = "HN"
        static let HR = "HR"
        static let HT = "HT"
        static let HU = "HU"
        static let ID = "ID"
        static let IE = "IE"
        static let IL = "IL"
        static let IM = "IM"
        static let IN = "IN"
        static let IO = "IO"
        static let IQ = "IQ"
        static let IR = "IR"
        static let IS = "IS"
        static let IT = "IT"
        static let JE = "JE"
        static let JM = "JM"
        static let JO = "JO"
        static let JP = "JP"
        static let KE = "KE"
        static let KG = "KG"
        static let KH = "KH"
        static let KI = "KI"
        static let KM = "KM"
        static let KN = "KN"
        static let KP = "KP"
        static let KR = "KR"
        static let KW = "KW"
        static let KY = "KY"
        static let KZ = "KZ"
        static let LA = "LA"
        static let LB = "LB"
        static let LC = "LC"
        static let LI = "LI"
        static let LK = "LK"
        static let LR = "LR"
        static let LS = "LS"
        static let LT = "LT"
        static let LU = "LU"
        static let LV = "LV"
        static let LY = "LY"
        static let MA = "MA"
        static let MC = "MC"
        static let MD = "MD"
        static let ME = "ME"
        static let MF = "MF"
        static let MG = "MG"
        static let MH = "MH"
        static let MK = "MK"
        static let ML = "ML"
        static let MM = "MM"
        static let MN = "MN"
        static let MO = "MO"
        static let MP = "MP"
        static let MQ = "MQ"
        static let MR = "MR"
        static let MS = "MS"
        static let MT = "MT"
        static let MU = "MU"
        static let MV = "MV"
        static let MW = "MW"
        static let MX = "MX"
        static let MY = "MY"
        static let MZ = "MZ"
        static let NA = "NA"
        static let NC = "NC"
        static let NE = "NE"
        static let NF = "NF"
        static let NG = "NG"
        static let NI = "NI"
        static let NL = "NL"
        static let NO = "NO"
        static let NP = "NP"
        static let NR = "NR"
        static let NU = "NU"
        static let NZ = "NZ"
        static let OM = "OM"
        static let PA = "PA"
        static let PE = "PE"
        static let PF = "PF"
        static let PG = "PG"
        static let PH = "PH"
        static let PK = "PK"
        static let PL = "PL"
        static let PM = "PM"
        static let PN = "PN"
        static let PR = "PR"
        static let PS = "PS"
        static let PT = "PT"
        static let PW = "PW"
        static let PY = "PY"
        static let QA = "QA"
        static let RE = "RE"
        static let RO = "RO"
        static let RS = "RS"
        static let RU = "RU"
        static let RW = "RW"
        static let SA = "SA"
        static let SB = "SB"
        static let SC = "SC"
        static let SD = "SD"
        static let SE = "SE"
        static let SG = "SG"
        static let SH = "SH"
        static let SI = "SI"
        static let SJ = "SJ"
        static let SK = "SK"
        static let SL = "SL"
        static let SM = "SM"
        static let SN = "SN"
        static let SO = "SO"
        static let SR = "SR"
        static let SS = "SS"
        static let ST = "ST"
        static let SV = "SV"
        static let SY = "SY"
        static let SZ = "SZ"
        static let TC = "TC"
        static let TD = "TD"
        static let TF = "TF"
        static let TG = "TG"
        static let TH = "TH"
        static let TJ = "TJ"
        static let TK = "TK"
        static let TL = "TL"
        static let TM = "TM"
        static let TN = "TN"
        static let TO = "TO"
        static let TR = "TR"
        static let TT = "TT"
        static let TV = "TV"
        static let TW = "TW"
        static let TZ = "TZ"
        static let UA = "UA"
        static let UG = "UG"
        static let UM = "UM"
        static let US = "US"
        static let UY = "UY"
        static let UZ = "UZ"
        static let VA = "VA"
        static let VC = "VC"
        static let VE = "VE"
        static let VG = "VG"
        static let VI = "VI"
        static let VN = "VN"
        static let VU = "VU"
        static let WF = "WF"
        static let WS = "WS"
        static let YE = "YE"
        static let YT = "YT"
        static let ZA = "ZA"
        static let ZM = "ZM"
        static let ZW = "ZW"
        static let All = "All"

        static let Afghan: (String, String, [String]) = ("afghani", "Afghan", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
        static let African: (String, String, [String]) = ("african", "African" , [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
        static let Senegalese: (String, String, [String]) = ("senegalese", "Senegalese" , [IT, CA, FR, US, BE])
        static let SouthAfrican: (String, String, [String]) = ("southafrican", "South African",  [IT, AU, CA, FR, US, BE])
        static let AmericanNew: (String, String, [String]) = ("newamerican", "American (New)", [SE, GB, US, IE, NO, DK])
        static let AmericanTraditional: (String, String, [String]) = ("tradamerican", "American (Traditional)", [All])
        static let Andalusian: (String, String, [String]) = ("andalusian", "Andalusian", [IT, ES])
        static let Arabian: (String, String, [String]) = ("arabian", "Arabian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let ArabPizza: (String, String, [String]) = ("arabpizza", "Arab Pizza", [BR])
        static let Argentine: (String, String, [String]) = ("argentine", "Argentine", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Armenian: (String, String, [String]) = ("armenian", "Armenian", [IT, CZ, US, BE, ES, AR, GB, TR, FR, PL])
        static let AsianFusion: (String, String, [String]) = ("asianfusion", "Asian Fusion", [All])
        static let Asturian: (String, String, [String]) = ("asturian", "Asturian", ["ES"])
        static let Australian: (String, String, [String]) = ("australian", "Australian", ["All"])
        static let Austrian: (String, String, [String]) = ("austrian", "Austrian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Baguettes: (String, String, [String]) = ("baguettes", "Baguettes", [IT, CZ, PT, SE, DE, TR, MX, NO])
        static let Bangladeshi: (String, String, [String]) = ("bangladeshi", "Bangladeshi", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Barbeque: (String, String, [String]) = ("bbq", "Barbeque", [AR, AT, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Basque: (String, String, [String]) = ("basque", "Basque", [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
        static let Bavarian: (String, String, [String]) = ("bavarian", "Bavarian", [CH, DE, AT])
        static let BeerGarden: (String, String, [String]) = ("beergarden", "Beer Garden", [CH, CZ, DE, AT])
        static let BeerHall: (String, String, [String]) = ("beerhall", "Beer Hall", [CH, DE, AT])
        static let Beisl: (String, String, [String]) = ("beisl", "Beisl", [AT])
        static let Belgian: (String, String, [String]) = ("belgian", "Belgian", [All])
        static let Flemish: (String, String, [String]) = ("flemish", "Flemish", [FR])
        static let Bistros: (String, String, [String]) = ("bistros", "Bistros", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
        static let BlackSea: (String, String, [String]) = ("blacksea", "Black Sea", [TR])
        static let Brasseries: (String, String, [String]) = ("brasseries", "Brasseries", [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Brazilian: (String, String, [String]) = ("brazilian", "Brazilian", [All])
        static let BrazilianEmpanadas: (String, String, [String]) = ("brazilianempanadas", "Brazilian Empanadas", [BR])
        static let CentralBrazilian: (String, String, [String]) = ("centralbrazilian", "Central Brazilian", [BR])
        static let NortheasternBrazilian: (String, String, [String]) = ("northeasternbrazilian", "Northeastern Brazilian", [BR])
        static let NorthernBrazilian: (String, String, [String]) = ("northernbrazilian", "Northern Brazilian", [BR])
        static let Rodizios: (String, String, [String]) = ("rodizios", "Rodizios", [BR, PT, AR])
        static let BreakfastBrunch: (String, String, [String]) = ("breakfast_brunch", "Breakfast/Brunch", [All])
        static let British: (String, String, [String]) = ("british", "British", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Buffets: (String, String, [String]) = ("buffets", "Buffets", [All])
        static let Bulgarian: (String, String, [String]) = ("bulgarian", "Bulgarian", [AR, AT, AU, BE, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, PH, PL, PT, SE, TW])
        static let Burgers: (String, String, [String]) = ("burgers", "Burgers", [All])
        static let Burmese: (String, String, [String]) = ("burmese", "Burmese", [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Cafes: (String, String, [String]) = ("cafes", "Cafes", [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let ThemedCafes: (String, String, [String]) = ("themedcafes", "Themed Cafes", [JP, NL, US, BE, PH, HK, DE, MY, FR, PL, FI, TW, SG])
        static let Cafeteria: (String, String, [String]) =  ("cafeteria", "Cafeteria", [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, TR, TW, US])
        static let CajunCreole: (String, String, [String]) = ("cajun", "Cajun", [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TR, TW, US])
        static let Cambodian: (String, String, [String]) = ("cambodian", "Cambodian", [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Canadian: (String, String, [String]) = ("newcanadian", "Canadian (New)", [CA])
        static let Canteen: (String, String, [String]) = ("canteen", "Canteen", [IT, CZ, JP, AT, CH, NL, BE, DE, PL, FI, NO, DK])
        static let Caribbean: (String, String, [String]) = ("caribbean", "Caribbean", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Dominican: (String, String, [String]) = ("dominican", "Dominican", [US])
        static let Haitian: (String, String, [String]) =  ("haitian", "Haitian", [US, CA])
        static let PuertoRican: (String, String, [String]) = ("puertorican", "Pueto Rican", [US])
        static let Trinidadian: (String, String, [String]) = ("trinidadian", "Trinidadian", [US])
        static let Catalan: (String, String, [String]) = ("catalan", "Catalan", [IT, PT, CL, US, ES, AR, TR, MX, FR])
        static let Cheesesteaks: (String, String, [String]) = ("cheesesteaks", "Cheesesteaks", [GB, AU, CA, NL, PL, US, IE])
        static let ChickenShop: (String, String, [String]) = ("chickenshop", "Chicken Shop", [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let ChickenWings: (String, String, [String]) = ("chicken_wings", "Chicken Wings", [AR, AT, BR, CA, CZ, DE, GB, HK, IE, MX, PL, SE, SG, TR, TW, US])
        static let Chilean: (String, String, [String]) = ("chilean", "Chilean", [BR, FI, FR, CL])
        static let Chinese: (String, String, [String]) = ("chinese", "Chinese", [All])
        static let Cantonese: (String, String, [String]) = ("cantonese", "Cantonese", [IT, JP, NZ, AU, NL, US, BE, SE, AR, GB, HK, MY, FR, TW, SG])
        static let Congee: (String, String, [String]) = ("congee", "Congee", [TW, MY, HK, SG])
        static let DimSum: (String, String, [String]) = ("dimsum", "Dim Sum", [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Fuzhou: (String, String, [String]) = ("fuzhou", "Fuzhou", [TW, MY, HK, SG])
        static let Hainan: (String, String, [String]) = ("hainan", "Hainan", [PH, HK, MY, US, SG])
        static let Hakka: (String, String, [String]) = ("hakka", "Hakka", [PH, HK, MY, CA, TW, SG])
        static let Henghwa: (String, String, [String]) = ("henghwa", "Hengwa", [TW, MY, HK, SG])
        static let Hokkien: (String, String, [String]) = ("hokkien", "Hokkien", [TW, MY, HK, SG])
        static let Hunan: (String, String, [String]) = ("hunan", "Hunan", [HK, MY, FR, TW, SG])
        static let Pekinese: (String, String, [String]) = ("pekinese", "Pekinese", [IT, JP, HK, MY, FR, TW, SG])
        static let Shanghainese: (String, String, [String]) = ("shanghainese", "Shanghainese", [IT, JP, AU, US, BE, SE, HK, MY, FR, TW, SG])
        static let Szechuan: (String, String, [String]) = ("szechuan", "Szechuan", [NZ, JP, AU, US, IE, HK, GB, MY, FR, TW, SG])
        static let Teochew: (String, String, [String]) = ("teochew", "Teochew", [TW, MY, HK, SG])
        static let ComfortFood: (String, String, [String]) = ("comfortfood", "Comfort Food", [JP, AR, CA, MX, CL, US, FI])
        static let Corsican: (String, String, [String]) = ("corsican", "Corsican", [BE, FR])
        static let Creperies: (String, String, [String]) = ("creperies", "Creperies", [All])
        static let Cuban: (String, String, [String]) = ("cuban", "Cuban", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
        static let CurrySausage: (String, String, [String]) = ("currysausage", "Curry Sausage", [CH, DE, AT])
        static let Cypriot: (String, String, [String]) = ("cypriot", "Cypriot", [CH, DE, AT])
        static let Czech: (String, String, [String]) = ("czech", "Czech", [IT, CZ, AU, US, IE, BE, SE, DE, GB, CA, FR, PL, FI, NO, DK])
        static let CzechSlovakian: (String, String, [String]) = ("czechslovakian", "Czech Slovakian", [PT, MX, AR])
        static let Danish: (String, String, [String]) = ("danish", "Danish", [FR, SE, NO, DK])
        static let Delis: (String, String, [String]) = ("delis", "Delis", [AR, AT, AU, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NO, NZ, PH, PL, SG, TR, TW, US])
        static let Diners: (String, String, [String]) = ("diners", "Diners", [AR, AT, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
        static let DinnerTheater: (String, String, [String]) = ("dinnertheater", "Dinner Theater", [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Dumplings: (String, String, [String]) = ("dumplings", "Dumplings", [JP])
        static let EasternEuropean: (String, String, [String]) = ("eastern_european", "Eastern European", [CZ, AU, FR, NO, DK])
        static let Ethiopian: (String, String, [String]) = ("ethiopian", "Ethiopian", [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
        static let FastFood: (String, String, [String]) = ("fast_food", "Fast Food", [All])
        static let Filipino: (String, String, [String]) = ("filipino", "Filipino", [AR, AT, AU, BE, BR, CA, CH, CL, DE, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
        static let Fischbroetchen: (String, String, [String]) = ("fischbroetchen", "Fischbroetchen", [DE])
        static let FishChips: (String, String, [String]) = ("fishnchips", "Fish and Chips", [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
        static let Flatbread: (String, String, [String]) = ("flatbread", "Flatbread", [DE, AT, CH, PL, DK])
        static let Fondue: (String, String, [String]) = ("fondue", "Fondue", [AR, AT, AU, BE, BR, CA, CH, CL, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let FoodCourt: (String, String, [String]) = ("food_court", "Food Court", [AT, AU, BE, BR, CA, CH, CZ, DE, DK, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PT, SE, SG, US])
        static let FoodStands: (String, String, [String]) = ("foodstands", "Food Stands", [All])
        static let Freiduria: (String, String, [String]) = ("freiduria", "Freiduria", [ES, AR, MX, CL])
        static let French: (String, String, [String]) = ("french", "French", [All])
        static let HotDogs: (String, String, [String]) = ("hot_dogs", "Hot Dogs", [All])
        static let Alsatian: (String, String, [String]) = ("alsatian", "Alsatian", [DE, FR])
        static let Auvergnat: (String, String, [String]) = ("auvergnat", "Auvergnat", [FR])
        static let Berrichon: (String, String, [String]) = ("berrichon", "Berrichon", [FR])
        static let Bourguignon: (String, String, [String]) = ("bourguignon", "Bourguignon", [FR])
        static let Mauritius: (String, String, [String]) = ("mauritius", "Mauritius", [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
        static let Nicoise: (String, String, [String]) = ("nicois", "Nicoise", [FR])
        static let Provencal: (String, String, [String]) = ("provencal", "Provencal", [FR])
        static let Reunion: (String, String, [String]) = ("reunion", "Reunion", [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
        static let FrenchSouthwest: (String, String, [String]) = ("sud_ouest", "French Southwest", [BE, FR])
        static let Galician: (String, String, [String]) = ("galician", "Galician", [PT, ES])
        static let GameMeat: (String, String, [String]) = ("gamemeat", "GameMeat", [AT, AU, BE, CH, CZ, DE, DK, ES, FR, GB, IE, IT, NL, NO, NZ, PL, SE, SG, US])
        static let Gastropubs: (String, String, [String]) = ("gastropubs", "Gastropubs", [All])
        static let Georgian: (String, String, [String]) = ("georgian", "Georgian", [CZ, DE, AT, GB, CH, PL, FI])
        static let German: (String, String, [String]) = ("german", "German", [All])
        static let Baden: (String, String, [String]) = ("baden", "Baden", [DE])
        static let EasternGerman: (String, String, [String]) = ("easterngerman", "Eastern German", [DE])
        static let Franconian: (String, String, [String]) = ("franconian", "Franconian", [DE])
        static let Hessian: (String, String, [String]) = ("hessian", "Hessian", [DE])
        static let NorthernGerman: (String, String, [String]) = ("northerngerman", "Northern German", [DE])
        static let Palatine: (String, String, [String]) = ("palatine", "Palatine", [DE])
        static let Rhinelandian: (String, String, [String]) = ("rhinelandian", "Rhinelandian", [DE])
        static let Giblets: (String, String, [String]) = ("giblets", "Giblets", [TR])
        static let GlutenFree: (String, String, [String]) = ("gluten_free", "Gluten Free", [All])
        static let Greek: (String, String, [String]) = ("greek", "Greek", [All])
        static let Guamanian: (String, String, [String]) = ("guamanian", "Guamanian", [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
        static let Halal: (String, String, [String]) = ("halal", "Halal", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Hawaiian: (String, String, [String]) = ("hawaiian", "Hawaiian", [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Heuriger: (String, String, [String]) = ("heuriger", "Heuriger", [AT])
        static let HimalayanNepalese: (String, String, [String]) = ("himalayan", "Himalayan Nepalese", [All])
        static let Honduran: (String, String, [String]) = ("honduran", "Honduran", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
        static let HongKongStyleCafe: (String, String, [String]) = ("hkcafe", "Hong Kong Style Cafe", [TW, US, HK])
        static let HotPot: (String, String, [String]) = ("hotpot", "Hot Pot", [JP, US, PH, SE, HK, MY, CA, FR, BR, TW, SG])
        static let Hungarian: (String, String, [String]) = ("hungarian", "Hungarian", [All])
        static let Iberian: (String, String, [String]) = ("iberian", "Iberian", [US, CA, PT])
        static let Indian: (String, String, [String]) = ("indpak", "Indian", [All])
        static let Indonesian: (String, String, [String]) = ("indonesian", "Indonesian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let International: (String, String, [String]) = ("international", "International", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TW])
        static let Irish: (String, String, [String]) = ("irish", "Irish", [All])
        static let IslandPub: (String, String, [String]) = ("island_pub", "Island Pub", [SE])
        static let Israeli: (String, String, [String]) = ("israeli", "Israeli", [CH, CZ, DE, AT])
        static let Italian: (String, String, [String]) = ("italian", "Italian", [All])
        static let Abruzzese: (String, String, [String]) = ("abruzzese", "Abruzzese", [IT])
        static let Altoatesine: (String, String, [String]) = ("altoatesine", "Altoatesine", [IT])
        static let Apulian: (String, String, [String]) = ("apulian", "Apulian", [IT, FR])
        static let Calabrian: (String, String, [String]) = ("calabrian", "Calabrian", [IT, US, FR])
        static let Cucinacampana: (String, String, [String]) = ("cucinacampana", "Cucinacampana", [IT])
        static let Emilian: (String, String, [String]) = ("emilian", "Emilian", [IT])
        static let Friulan: (String, String, [String]) = ("friulan", "Friulan", [IT])
        static let Ligurian: (String, String, [String]) = ("ligurian", "Ligurian", [IT, FR])
        static let Lumbard: (String, String, [String]) = ("lumbard", "Lumbard", [IT])
        static let Napoletana: (String, String, [String]) = ("napoletana", "Napoletana", [IT, CZ, FR])
        static let Piemonte: (String, String, [String]) = ("piemonte", "Piemonte", [IT, FR])
        static let Roman: (String, String, [String]) = ("roman", "Roman", [IT, JP, FR])
        static let Sardinian: (String, String, [String]) = ("sardinian", "Sardinian", [IT, US, FR])
        static let Sicilian: (String, String, [String]) = ("sicilian", "Sicilian", [IT, CZ, FR, PL, US])
        static let Tuscan: (String, String, [String]) = ("tuscan", "Tuscan", [IT, US, FR])
        static let Venetian: (String, String, [String]) = ("venetian", "Venetian", [IT, FR])
        static let Japanese: (String, String, [String]) = ("japanese", "Japanese", [All])
        static let Blowfish: (String, String, [String]) = ("blowfish", "Blowfish", [JP])
        static let ConveyorSushi: (String, String, [String]) = ("conveyorsushi", "Conveyor Belt Sushi", [HK, US, AT, SE, IT, TW, NL, SG, PL, CH, DE, JP, BE])
        static let Donburi: (String, String, [String]) = ("donburi", "Donburi", [TW, JP, HK])
        static let Gyudon: (String, String, [String]) = ("gyudon", "Gyudon", [JP])
        static let Oyakodon: (String, String, [String]) = ("oyakodon", "Oyakodon", [JP])
        static let HandRolls: (String, String, [String]) = ("handrolls", "HandRolls", [BR, TW])
        static let Horumon: (String, String, [String]) = ("horumon", "Horumon", [TW, JP])
        static let Izakaya: (String, String, [String]) = ("izakaya", "Izakaya", [NZ, JP, AU, US, HK, MX, BR, TW, SG])
        static let JapaneseCurry: (String, String, [String]) = ("japacurry", "Japanese Curry", [JP, HK, US, TW, SG])
        static let Kaiseki: (String, String, [String]) = ("kaiseki", "Kaiseki", [TW, JP])
        static let Kushikatsu: (String, String, [String]) = ("kushikatsu", "Kushikatsu", [JP])
        static let Oden: (String, String, [String]) = ("oden", "Oden", [TW, JP])
        static let Okinawan: (String, String, [String]) = ("okinawan", "Okinawan", [JP])
        static let Okonomiyaki: (String, String, [String]) = ("okonomiyaki", "Okonomiyaki", [TW, JP])
        static let Onigiri: (String, String, [String]) = ("onigiri", "Onigiri", [TW, JP])
        static let Ramen: (String, String, [String]) = ("ramen", "Ramen", [All])
        static let Robatayaki: (String, String, [String]) = ("robatayaki", "Robatayaki", [TW, JP, HK])
        static let Soba: (String, String, [String]) = ("soba", "Soba", [TW, JP])
        static let Sukiyaki: (String, String, [String]) = ("sukiyaki", "Sukiyaki", [TW, JP])
        static let Takoyaki: (String, String, [String]) = ("takoyaki", "Takoyaki", [TW, JP])
        static let Tempura: (String, String, [String]) = ("tempura", "Tempura", [TW, SG, JP])
        static let Teppanyaki: (String, String, [String]) = ("teppanyaki", "Teppanyaki", [NZ, JP, AU, US, HK, MX, TW, SG])
        static let Tonkatsu: (String, String, [String]) = ("tonkatsu", "Tonkatsu", [TW, SG, JP])
        static let Udon: (String, String, [String]) = ("udon", "Udon", [JP, SE, HK, FI, TW, NO, DK])
        static let Unagi: (String, String, [String]) = ("unagi", "Unagi", [TW, JP])
        static let WesternStyleJapaneseFood: (String, String, [String]) = ("westernjapanese", "Western Style Japanese Food", [TW, SG, JP])
        static let Yakiniku: (String, String, [String]) = ("yakiniku", "Yakiniku", [TW, SG, JP])
        static let Yakitori: (String, String, [String]) = ("yakitori", "Yakitori", [TW, SG, JP])
        static let Jewish: (String, String, [String]) = ("jewish", "Jewish", [PL, IT, DE])
        static let Kebab: (String, String, [String]) = ("kebab", "Kebab", [All])
        static let Kopitiam: (String, String, [String])  = ("kopitiam", "Kopitiam", [MY, SG])
        static let Korean: (String, String, [String]) = ("korean", "Korean", [All])
        static let Kosher: (String, String, [String]) = ("kosher", "Kosher", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Kurdish: (String, String, [String]) = ("kurdish", "Kurdish", [SE, NO])
        static let Laos: (String, String, [String]) = ("laos", "Laos", [AU])
        static let Laotian: (String, String, [String]) = ("laotian", "Laotian", [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let LatinAmerican: (String, String, [String]) = ("latin", "Latin American", [All])
        static let Colombian: (String, String, [String]) = ("colombian", "Colombian", [CL, US, BE, ES, AR, CA, MX, FR, FI])
        static let Salvadoran: (String, String, [String]) = ("salvadoran", "Salvadoran", [US, CA])
        static let Venezuelan: (String, String, [String]) = ("venezuelan", "Venezuelan", [ES, AR, PT, CA, FR, CL, US])
        static let LiveRawFood: (String, String, [String]) = ("raw_food", "Live Raw Food", [All])
        static let Lyonnais: (String, String, [String]) = ("lyonnais", "Lyonnais", [BE, FR])
        static let Malaysian: (String, String, [String]) = ("malaysian", "Malaysian", [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Mamak: (String, String, [String]) = ("mamak", "Mamak", [AU, MY])
        static let Nyonya: (String, String, [String]) = ("nyonya", "Nyonya", [AU, MY])
        static let Meatballs: (String, String, [String]) = ("meatballs", "Meatballs", [TR, BE, NL, FR])
        static let Mediterranean: (String, String, [String]) = ("mediterranean", "Mediterranean", [All])
        static let Falafel: (String, String, [String]) = ("falafel", "Falafel", [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
        static let Mexican: (String, String, [String]) = ("mexican", "Mexican", [All])
        static let EasternMexican: (String, String, [String]) = ("easternmexican", "Eastern Mexican", [MX])
        static let Jaliscan: (String, String, [String]) = ("jaliscan", "Jaliscan", [MX])
        static let NorthernMexican: (String, String, [String]) = ("northernmexican", "Northern Mexican", [MX])
        static let Oaxacan: (String, String, [String]) = ("oaxacan", "Oaxacan", [MX])
        static let Pueblan: (String, String, [String]) = ("pueblan", "Pueblan", [MX])
        static let Tacos: (String, String, [String]) = ("tacos", "Tacos", [US, MX])
        static let Tamales: (String, String, [String]) = ("tamales", "Tamales", [MX])
        static let Yucatan: (String, String, [String]) = ("yucatan", "Yucatan", [MX])
        static let MiddleEastern: (String, String, [String]) = ("mideastern", "Middle Eastern", [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Egyptian: (String, String, [String]) = ("egyptian", "Egyptian", [IT, CA, FR, US, BE])
        static let Lebanese: (String, String, [String]) = ("lebanese", "Lebanese", [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let MilkBars: (String, String, [String]) = ("milkbars", "Milk Bars", [AU, PL])
        static let ModernAustralian: (String, String, [String]) = ("modern_australian", "Modern Australian", [AU])
        static let ModernEuropean: (String, String, [String]) = ("modern_european", "Modern European", [All])
        static let Mongolian: (String, String, [String]) = ("mongolian", "Mongolian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Moroccan: (String, String, [String]) = ("moroccan", "Moroccan", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
        static let NewMexicanCuisine: (String, String, [String]) = ("newmexican", "New Mexican Cuisine", [US])
        static let NewZealand: (String, String, [String]) = ("newzealand", "New Zealand", [NZ])
        static let Nicaraguan: (String, String, [String]) = ("nicaraguan", "Nicaraguan", [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let NightFood: (String, String, [String]) = ("nightfood", "Night Food", [SE, TR, PL, NO, DK])
        static let Nikkei: (String, String, [String]) = ("nikkei", "Nikkei", [ES, AR, MX, CL, BR])
        static let Noodles: (String, String, [String]) = ("noodles", "Noodles", [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Norcinerie: (String, String, [String]) = ("norcinerie", "Norcinerie", [IT])
        static let OpenSandwiches: (String, String, [String]) = ("opensandwiches", "Open Sandwiches", [TR, SE, NO, DK])
        static let Oriental: (String, String, [String]) = ("oriental", "Oriental", [PT, DE, AT, CH, FR])
        static let PFComercial: (String, String, [String]) = ("pfcomercial", "PFComercial", [BR])
        static let Pakistani: (String, String, [String]) = ("pakistani", "PFComercial", [All])
        static let PanAsian: (String, String, [String]) = ("panasian", "PanAsian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let ParentCafes: (String, String, [String]) = ("eltern_cafes", "ParentCafes", [CH, DE, AT])
        static let Parma: (String, String, [String]) = ("parma", "Parma", [AU])
        static let PersianIranian: (String, String, [String]) = ("persian", "Persian Iranian", [All])
        static let Peruvian: (String, String, [String]) = ("peruvian", "Peruvian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
        static let Pita: (String, String, [String]) = ("pita", "Pita", [TR])
        static let Pizza: (String, String, [String]) = ("pizza", "Pizza", [All])
        static let Polish: (String, String, [String]) = ("polish", "Polish", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
        static let Pierogis: (String, String, [String]) = ("pierogis", "Pierogis", [PL])
        static let PopUpRestaurants: (String, String, [String]) = ("popuprestaurants", "Pop-Up Restaurants", [NL, US, IE, BE, PH, SE, DE, GB, HK, MY, FR, TW, SG, NO, DK])
        static let Portuguese: (String, String, [String]) = ("portuguese", "Portuguese", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Alentejo: (String, String, [String]) = ("alentejo", "Alentejo", [PT])
        static let Algarve: (String, String, [String]) = ("algarve", "Algarve", [PT])
        static let Azores: (String, String, [String]) = ("azores", "Azores", [PT])
        static let Beira: (String, String, [String]) = ("beira", "Beira", [PT])
        static let FadoHouses: (String, String, [String]) = ("fado_houses", "Fado Houses", [PT])
        static let Madeira: (String, String, [String]) = ("madeira", "Madeira", [PT])
        static let Minho: (String, String, [String]) = ("minho", "Minho", [PT])
        static let Ribatejo: (String, String, [String]) = ("ribatejo", "Ribatejo", [PT])
        static let TrasosMontes: (String, String, [String]) = ("tras_os_montes", "Tras-os-Montes", [PT])
        static let Potatoes: (String, String, [String]) = ("potatoes", "Potatoes", [AU, CH, DE, AT])
        static let Poutineries: (String, String, [String]) = ("poutineries", "Poutineries", [US, CA])
        static let PubFood: (String, String, [String]) = ("pubfood", "Pub Food", [AU])
        static let Rice: (String, String, [String]) = ("riceshop", "Rice", [JP, TR])
        static let Romanian: (String, String, [String]) = ("romanian", "Romanian", [CZ, AT, CH, BE, ES, DE, FR, PL])
        static let RotisserieChicken: (String, String, [String]) = ("rotisserie_chicken", "Rotisserie Chicken", [IT, NZ, PT, AU, NL, CL, BE, ES, AR, MX, FR, BR, PL])
        static let Russian: (String, String, [String]) = ("russian", "Russian", [All])
        static let Salad: (String, String, [String]) = ("salad", "Salad", [All])
        static let Sandwiches: (String, String, [String]) = ("sandwiches", "Sandwiches", [All])
        static let Scandinavian: (String, String, [String]) = ("scandinavian", "Scandinavian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
        static let Schnitzel: (String, String, [String]) = ("schnitzel", "Schnitzel", [CH, PL, DE, AT])
        static let Scottish: (String, String, [String]) = ("scottish", "Scottish", [DE, GB, AT, CH, CA, US, IE])
        static let Seafood: (String, String, [String]) = ("seafood", "Seafood", [All])
        static let SerboCroatian: (String, String, [String]) = ("serbocroatian", "Serbo Croatian", [IT, CZ, AT, CH, CL, BE, SE, AR, DE, FR, PL])
        static let SignatureCuisine: (String, String, [String]) = ("signature_cuisine", "Signature Cuisine", [PT, CL, ES, AR, SE, MX, NO, DK])
        static let Singaporean: (String, String, [String]) = ("singaporean", "Singaporean", [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let Slovakian: (String, String, [String]) = ("slovakian", "Slovakian", [IT, CZ, AU, US, IE, BE, GB, CA, FR, PL])
        static let SoulFood: (String, String, [String]) = ("soulfood", "Soul Food", [NL, US, IE, ES, SE, GB, CA, PL, NO])
        static let Soup: (String, String, [String]) = ("soup", "Soup", [All])
        static let Southern: (String, String, [String]) = ("southern", "Southern", [NZ, NL, US, IE, SE, GB, TR, CA, PL])
        static let Spanish: (String, String, [String]) = ("spanish", "Spanish", [All])
        static let ArroceriaPaella: (String, String, [String]) = ("arroceria_paella", "Arroceria Paella", [ES])
        static let SriLankan: (String, String, [String]) = ("srilankan", "Sri Lankan", [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
        static let Steakhouses: (String, String, [String]) = ("steak", "Steakhouses", [All])
        static let SupperClubs: (String, String, [String]) = ("supperclubs", "Supper Clubs", [US, CA, ES, GB])
        static let SushiBars: (String, String, [String]) = ("sushi", "Sushi Bars", [All])
        static let Swabian: (String, String, [String]) = ("swabian", "Swabian", [CH, DE, AT])
        static let Swedish: (String, String, [String]) = ("swedish", "Swedish", [SE])
        static let SwissFood: (String, String, [String]) = ("swissfood", "Swiss Food", [CZ, ES, DE, AR, CH, MX, CL])
        static let Syrian: (String, String, [String]) = ("syrian", "Syrian", [All])
        static let Tabernas: (String, String, [String]) = ("tabernas", "Tabernas", [PT, ES, TR])
        static let Taiwanese: (String, String, [String]) = ("taiwanese", "Taiwanese", [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
        static let TapasBars: (String, String, [String]) = ("tapas", "Tapas Bars", [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
        static let TapasSmallPlates: (String, String, [String]) = ("tapasmallplates", "Tapas Small Plates", [All])
        static let TavolaCalda: (String, String, [String]) = ("tavolacalda", "Tavola Calda", [IT])
        static let TexMex: (String, String, [String]) = ("tex-mex", "Tex Mex", [AR, AT, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
        static let Thai: (String, String, [String]) = ("thai", "Thai", [All])
        static let TraditionalNorwegian: (String, String, [String]) = ("norwegian", "Traditional Norwegian",  [NO, FR])
        static let TraditionalSwedish: (String, String, [String]) = ("traditional_swedish", "Traditional Swedish", [FI, SE])
        static let Trattorie: (String, String, [String]) = ("trattorie", "Trattorie", [IT, AR, CH, FR, CL, PL])
        static let Turkish: (String, String, [String]) = ("turkish", "Turkish", [All])
        static let CheeKufta: (String, String, [String]) = ("cheekufta", "CheeKufta", [TR])
        static let Gozleme: (String, String, [String]) = ("gozleme", "Gozleme", [TR])
        static let HomemadeFood: (String, String, [String]) = ("homemadefood", "Homemade Food", [TR])
        static let Lahmacun: (String, String, [String]) = ("lahmacun", "Lahmacun", [TR])
        static let OttomanCuisine: (String, String, [String]) = ("ottomancuisine", "Ottoman Cuisine", [TR])
        static let TurkishRavioli: (String, String, [String]) = ("turkishravioli", "Turkish Ravioli", [TR])
        static let Ukrainian: (String, String, [String]) = ("ukrainian", "Ukrainian", [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
        static let Uzbek: (String, String, [String]) = ("uzbek", "Uzbek", [US, CZ])
        static let Vegan: (String, String, [String]) = ("vegan", "Vegan", [All])
        static let Vegetarian: (String, String, [String]) = ("vegetarian", "Vegetarian", [All])
        static let Venison: (String, String, [String]) = ("venison", "Venison", [IT, CZ, NZ, AU, IE, GB, CA, PL, SG, NO, DK])
        static let Vietnamese: (String, String, [String]) = ("vietnamese", "Vietnamese", [All])
        static let Waffles: (String, String, [String]) = ("waffles", "Waffles", [All])
        static let Wok: (String, String, [String]) = ("wok", "Wok", [AT, BE, CH, CL, CZ, DE, DK, ES, FI, FR, MX, MY, NL, NO, PH, PT, SE])
        static let Wraps: (String, String, [String]) = ("wraps", "Wraps",  [CZ, SE, PT, TR, US, NO, DK])
        static let Yugoslav: (String, String, [String]) = ("yugoslav", "Yugoslav", [IT, PT, SE, AU, FR, BE])
        
        static let AllStyles: [(String, String, [String])] = [Afghan, African, Senegalese, SouthAfrican, AmericanNew, AmericanTraditional,Andalusian,Arabian,ArabPizza,Argentine,Armenian,AsianFusion,Asturian,Australian,Austrian,Baguettes,Bangladeshi,Barbeque,Basque,Bavarian,BeerGarden,BeerHall,Beisl,Belgian,Flemish,Bistros,BlackSea,Brasseries,Brazilian,BrazilianEmpanadas,CentralBrazilian,NortheasternBrazilian,NorthernBrazilian,Rodizios,BreakfastBrunch,British,Buffets,Buffets,Bulgarian,Burgers,Burmese,Cafes,ThemedCafes,Cafeteria,CajunCreole,Cambodian,Canadian,Canteen,Caribbean,Dominican,Haitian,PuertoRican,Trinidadian,Catalan,Cheesesteaks,ChickenShop,ChickenWings,Chilean,Chinese,Cantonese,Congee,DimSum,Fuzhou,Hainan,Hakka,Henghwa,Hokkien,Hunan,Pekinese,Shanghainese,Szechuan,Teochew,ComfortFood,Corsican,Creperies,Cuban,CurrySausage,Cypriot,Czech,CzechSlovakian,Danish,Delis,Diners,DinnerTheater,Dumplings,EasternEuropean,Ethiopian,FastFood,Filipino,Fischbroetchen,FishChips,Flatbread,Fondue,FoodCourt,FoodStands,Freiduria,French,HotDogs,Alsatian,Auvergnat,Berrichon,Bourguignon,Mauritius,Nicoise,Provencal,Reunion,FrenchSouthwest,Galician,GameMeat,Gastropubs,Georgian,German,Baden,EasternGerman,Franconian,Hessian,NorthernGerman,Palatine,Rhinelandian,Giblets,GlutenFree,Greek,Guamanian,Halal,Hawaiian,Heuriger,HimalayanNepalese,Honduran,HongKongStyleCafe,HotPot,Hungarian,Iberian,Indian,Indonesian,International,Irish,IslandPub,Israeli,Italian,Abruzzese,Altoatesine,Apulian,Calabrian,Cucinacampana,Emilian,Friulan,Ligurian,Lumbard,Napoletana,Piemonte,Roman,Sardinian,Sicilian,Tuscan,Venetian,Japanese,Blowfish,ConveyorSushi,Donburi,Gyudon,Oyakodon,HandRolls,Horumon,Izakaya,JapaneseCurry,Kaiseki,Kushikatsu,Oden,Okinawan,Okonomiyaki,Onigiri,Ramen,Robatayaki,Soba,Sukiyaki,Takoyaki,Tempura,Teppanyaki,Tonkatsu,Udon,Unagi,WesternStyleJapaneseFood,Yakiniku,Yakitori,Jewish,Kebab,Kopitiam,Korean,Kosher,Kurdish,Laos,Laotian,LatinAmerican,Colombian,Salvadoran,Venezuelan,LiveRawFood,Lyonnais,Malaysian,Mamak,Nyonya,Meatballs,Mediterranean,Falafel,Mexican,EasternMexican,Jaliscan,NorthernMexican,Oaxacan,Pueblan,Tacos,Tamales,Yucatan,MiddleEastern,Egyptian,Lebanese,MilkBars,ModernAustralian,ModernEuropean,Mongolian,Moroccan,NewMexicanCuisine,NewZealand,Nicaraguan,NightFood,Nikkei,Noodles,Norcinerie,OpenSandwiches,Oriental,PFComercial,Pakistani,PanAsian,ParentCafes,Parma,PersianIranian,Peruvian,Pita,Pizza,Polish,Pierogis,PopUpRestaurants,Portuguese,Alentejo,Algarve,Azores,Beira,FadoHouses,Madeira,Minho,Ribatejo,TrasosMontes,Potatoes,Poutineries,PubFood,Rice,Romanian,RotisserieChicken,Russian,Salad,Sandwiches,Sandwiches,Scandinavian,Schnitzel,Scottish,Seafood,SerboCroatian,SignatureCuisine,Slovakian,SoulFood,Soup,Southern,Spanish,ArroceriaPaella,SriLankan,Steakhouses,SupperClubs,SushiBars,Swabian,Swedish,SwissFood,Syrian,Tabernas,Taiwanese,TapasBars,TapasSmallPlates,TavolaCalda,TexMex,Thai,TraditionalNorwegian,TraditionalSwedish,Trattorie,Turkish,CheeKufta,Gozleme,HomemadeFood,Lahmacun,OttomanCuisine,TurkishRavioli,Ukrainian,Uzbek,Vegan,Vegetarian,Venison,Vietnamese,Waffles,Wok,Wraps,Yugoslav
        ]
    }
    
    struct YelpParameterKeys {
        static let AuthorizeURL = "https://api.yelp.com/oauth2/token"
        static let SearchURL = "https://api.yelp.com/v3/businesses/search"
        static let BusinessesURL = "https://api.yelp.com/v3/businesses"
        static let Post = "POST"
        static let Get = "GET"
        static let GrantType = "grant_type"
        static let ClientID = "client_id"
        static let ClientSecret = "client_secret"
        static let Bearer = "Bearer"
        static let Authorization = "Authorization"
        static let latitude = "latitude"
        static let longitude = "longitude"
        static let radius = "radius"
        static let term = "term"
        static let limit = "limit"
        static let offset = "offset"
        static let sort_by = "sort_by"
    }
    
    struct YelpParameterValues {
        static let GrantType = "client_credentials"
        static let ClientID = "HDrilhWJnIw7G_MyxOENJg"
        static let API_Key = "dSo_fC6R4hPg5QV3KoLxTjI-id-Euja6NF1Xq2Doz5QWvtIKEAbvIG1aVk5UnjKj3nHer0vTzFxoRZPL6Kfv_X_8N6fK25fU28N33ReGh4c7XZoVAsW4AHGf-iS2XnYx"
        static let restaurants = "restaurants"
        static let best_match = "best_match"
    }
    
    struct YelpResponseKeys {
        static let TokenType = "token_type"
        static let AccessToken = "access_token"
        
        static let id = "id"
        static let name = "name"
        static let coordinates = "coordinates"
        static let latitude = "latitude"
        static let longitude = "longitude"
        static let location = "location"
        static let display_address = "display_address"
        static let distance = "distance"
        static let phone = "phone"
        static let image_url = "image_url"
        static let price = "price"
        static let rating = "rating"
        static let review_count = "review_count"
        static let url = "url"
        static let categories = "categories"
        static let title = "title"
        static let photos = "photos"
        static let hours = "hours"
        static let open = "open"
        static let day = "day"
        static let start = "start"
        static let end = "end"
        static let total = "total"
        static let businesses = "businesses"
    }
    
    // MARK: - Application Constants
    struct Application {
//        static let RestaurantClassName = String(describing: Restaurant.self)
        static let textAnimationDuration = 0.3
        static let imageAnimationDuration = 0.5
        static let notificationDuration = 1.0
        static let randomStyleDuration = 1.5
        static let randomizerDuration = 0.1
        static let SaveFavoriteSuccess = "Saved to favorites."
        static let RemoveFavoriteSuccess = "Removed from favorites."
        static let YelpURL = "https://www.yelp.com/"
        static let Icons8URL = "https://icons8.com/"
    }
    
    struct ErrorMessages {
        static let Error = "Error"
        static let Authentication = "Failed to authenticate."
        static let Info = "Failed to obtain restaurant info."
        static let ZeroResults = "No results found."
        static let NoPhone = "This location has no phone number."
        static let GeocodeLocation = "Could not find the specified location."
        static let UserLocation = "Could not set user location."
        static let NeedLocation = "Location not set."
        static let GPS = "Failed to initialize GPS."
        static let URL = "Failed to open link."
        static let AddFavorite = "Could not add to favorites."
        static let RemoveFavorite = "Could not remove from favorites."
    }
//
//    struct Theme {
//        static let ThemeKey = "dayThemeOn"
//        static let MaxResultsKey = "maxResults"
//        static let Results_1 = 1
//        static let Results_5 = 5
//        static let Results_10 = 10
//        static let Blue = UIColor(red: 53.0/255.0, green: 120.0/255.0, blue: 246.0/255.0, alpha: 1)
//        static let DarkGray = UIColor(red: 30.0/255.0, green: 30.0/255.0, blue: 30.0/255.0, alpha: 1)
//        static let LightGray = UIColor(red: 240.0/255.0, green: 240.0/255.0, blue: 240.0/255.0, alpha: 1)
//        static let Black = UIColor(red: 20.0/255.0, green: 20.0/255.0, blue: 20.0/255.0, alpha: 1)
//        static let Yellow = UIColor(red: 255.0/255.0, green: 192.0/255.0, blue: 20.0/255.0, alpha: 1)
//        static let White = UIColor.white
//        static let Orange = UIColor.orange
//        static let Green = UIColor.green
//        static let Red = UIColor(red: 211.0/255.0, green: 35.0/255.0, blue: 35.0/255.0, alpha: 1)
//    }
    
}
